name: Push to GitHub npm
on:
  push:
    branches-ignore:
      - wip/*

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: "./utils"

    steps:
      - uses: actions/checkout@v3
      - uses: FrontEndDev-org/publish-node-package-action@v1
        with:
          target: github
