name: Publish to GitHub NPM

on:
  release:
    types:
      - published
      - edited
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@0.3.4
        with:
          key: kanekotic/merge-release@master
      - name: Publish
        uses: kanekotic/merge-release@master
        with: # Required, but ignored
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, but required
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional, but required
          NPM_CUSTOM_NPMRC: '\n'
          NPM_CONFIG_USERCONFIG: .npmrc
          NPM_REGISTRY_URL: https://npm.pkg.github.com
          DEPLOY_DIR: utils
          SRC_PACKAGE_DIR: utils
